name: first-time-setup
run-name: Setup

on:
  push:
    branches: [ main ]

# Only keep latest run of this workflow
concurrency:
  group: first-time-setup
  cancel-in-progress: true

permissions: 
  actions: write
  checks: write
  contents: write

jobs:
  first-time-setup:
    # Ensure this action is run only on the creation of the repository
    if: github.event.created == true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run first time setup script
        run: node .github/workflows/scripts/first-time-setup.js "${{ github.repository_owner }}" "${{ github.event.repository.name }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Adapt template automatically"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
